<a href="https://colab.research.google.com/github/GJebres/LHUBCapstoneProject/blob/main/CapstoneHRAnalytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1. Descriptive Analysis on IBM HR Data

In [4]:
import pandas as pd

#Getting the source data and display it
url = "https://raw.githubusercontent.com/GJebres/LHUBCapstoneProject/main/SourceData/"

#Reading the files
compensation = pd.read_csv(url + "Compensation.csv")
employees = pd.read_csv(url + "Employees.csv")
employment_status = pd.read_csv(url + "EmploymentStatus.csv")
experience = pd.read_csv(url + "Experience.csv")
performance = pd.read_csv(url + "Performance.csv")

print("COMPENSATION")
print(compensation.shape)
print(compensation.columns.tolist())
display(compensation.head(3))

print("EMPLOYEES")
print(employees.shape)
print(employees.columns.tolist())
display(employees.head(3))

print("EMPLOYMENT STATUS")
print(employment_status.shape)
print(employment_status.columns.tolist())
display(employment_status.head(3))

print("EXPERIENCE")
print(experience.shape)
print(experience.columns.tolist())
display(experience.head(3))

print("PERFORMANCE")
print(performance.shape)
print(performance.columns.tolist())
display(performance.head(3))

COMPENSATION
(1470, 7)
['EmployeeNumber', 'DailyRate', 'HourlyRate', 'MonthlyIncome', 'MonthlyRate', 'PercentSalaryHike', 'StockOptionLevel']

,EmployeeNumber,DailyRate,HourlyRate,MonthlyIncome,MonthlyRate,PercentSalaryHike,StockOptionLevel
0,1,1102,94,5993,19479,11,0
1,2,279,61,5130,24907,23,1
2,4,1373,92,2090,2396,15,0

EMPLOYEES
(1470, 14)
['EmployeeNumber', 'Age', 'Gender', 'MaritalStatus', 'Education', 'EducationField', 'Department', 'JobRole', 'JobLevel', 'BusinessTravel', 'DistanceFromHome', 'EmployeeCount', 'Over18', 'StandardHours']

,EmployeeNumber,Age,Gender,MaritalStatus,Education,EducationField,Department,JobRole,JobLevel,BusinessTravel,DistanceFromHome,EmployeeCount,Over18,StandardHours
0,1,41.0,Female,Single,2,Life Sciences,Sales,Sales Executive,2,Travel_Rarely,1,1,Y,80
1,2,49.0,Male,Married,1,Life Sciences,Research & Development,Research Scientist,2,Travel_Frequently,8,1,Y,80
2,4,37.0,Male,Single,2,Other,Research & Development,Laboratory Technician,1,Travel_Rarely,2,1,Y,80

EMPLOYMENT STATUS
(1470, 3)
['EmployeeNumber', 'Attrition', 'OverTime']

   EmployeeNumber Attrition OverTime
0               1       Yes      Yes
1               2        No       No
2               4       Yes      Yes

EXPERIENCE
(1470, 8)
['EmployeeNumber', 'NumCompaniesWorked', 'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

,EmployeeNumber,NumCompaniesWorked,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,1,8,8,0,6,4,0,5
1,2,1,10,3,10,7,1,7
2,4,6,7,3,0,0,0,0

PERFORMANCE
(1470, 7)
['EmployeeNumber', 'PerformanceRating', 'EnvironmentSatisfaction', 'JobInvolvement', 'JobSatisfaction', 'RelationshipSatisfaction', 'WorkLifeBalance']

,EmployeeNumber,PerformanceRating,EnvironmentSatisfaction,JobInvolvement,JobSatisfaction,RelationshipSatisfaction,WorkLifeBalance
0,1,3,2,3,4,1,1
1,2,4,3,2,2,4,3
2,4,3,4,2,3,2,3

In [5]:
#Check if there are missing values
print("Compensation")
print(compensation.isnull().sum())

print("Employees")
print(employees.isnull().sum())

print("Employment Status")
print(employment_status.isnull().sum())

print("Experience")
print(experience.isnull().sum())

print("Performance")
print(performance.isnull().sum())

Compensation
EmployeeNumber       0
DailyRate            0
HourlyRate           0
MonthlyIncome        0
MonthlyRate          0
PercentSalaryHike    0
StockOptionLevel     0
dtype: int64
Employees
EmployeeNumber      0
Age                 5
Gender              0
MaritalStatus       0
Education           0
EducationField      0
Department          0
JobRole             0
JobLevel            0
BusinessTravel      0
DistanceFromHome    0
EmployeeCount       0
Over18              0
StandardHours       0
dtype: int64
Employment Status
EmployeeNumber    0
Attrition         0
OverTime          0
dtype: int64
Experience
EmployeeNumber             0
NumCompaniesWorked         0
TotalWorkingYears          0
TrainingTimesLastYear      0
YearsAtCompany             0
YearsInCurrentRole         0
YearsSinceLastPromotion    0
YearsWithCurrManager       0
dtype: int64
Performance
EmployeeNumber              0
PerformanceRating           0
EnvironmentSatisfaction     0
JobInvolvement              0
JobSatisfaction             0
RelationshipSatisfaction    0
WorkLifeBalance             0
dtype: int64

In [7]:
#Check if there are duplicate rows
print("Compensation duplicates:", compensation.duplicated().sum())
print("Employees duplicates:", employees.duplicated().sum())
print("Employment Status duplicates:", employment_status.duplicated().sum())
print("Experience duplicates:", experience.duplicated().sum())
print("Performance duplicates:", performance.duplicated().sum())

Compensation duplicates: 0
Employees duplicates: 0
Employment Status duplicates: 0
Experience duplicates: 0
Performance duplicates: 0

In [8]:
#Check the data information
print("Compensation")
compensation.info()

print("Employees")
employees.info()

print("Employment Status")
employment_status.info()

print("Experience")
experience.info()

print("Performance")
performance.info()

Compensation
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   EmployeeNumber     1470 non-null   int64
 1   DailyRate          1470 non-null   int64
 2   HourlyRate         1470 non-null   int64
 3   MonthlyIncome      1470 non-null   int64
 4   MonthlyRate        1470 non-null   int64
 5   PercentSalaryHike  1470 non-null   int64
 6   StockOptionLevel   1470 non-null   int64
dtypes: int64(7)
memory usage: 80.5 KB
Employees
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmployeeNumber    1470 non-null   int64
 1   Age               1465 non-null   float64
 2   Gender            1470 non-null   object
 3   MaritalStatus     1470 non-null   object
 4   Education         1470 non-null   int64
 5   EducationField    1470 non-null   object
 6   Department        1470 non-null   object
 7   JobRole           1470 non-null   object
 8   JobLevel          1470 non-null   int64
 9   BusinessTravel    1470 non-null   object
 10  DistanceFromHome  1470 non-null   int64
 11  EmployeeCount     1470 non-null   int64
 12  Over18            1470 non-null   object
 13  StandardHours     1470 non-null   int64
dtypes: float64(1), int64(6), object(7)
memory usage: 160.9+ KB
Employment Status
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   EmployeeNumber  1470 non-null   int64
 1   Attrition       1470 non-null   object
 2   OverTime        1470 non-null   object
dtypes: int64(1), object(2)
memory usage: 34.6+ KB
Experience
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   EmployeeNumber           1470 non-null   int64
 1   NumCompaniesWorked       1470 non-null   int64
 2   TotalWorkingYears        1470 non-null   int64
 3   TrainingTimesLastYear    1470 non-null   int64
 4   YearsAtCompany           1470 non-null   int64
 5   YearsInCurrentRole       1470 non-null   int64
 6   YearsSinceLastPromotion  1470 non-null   int64
 7   YearsWithCurrManager     1470 non-null   int64
dtypes: int64(8)
memory usage: 92.0 KB
Performance
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmployeeNumber            1470 non-null   int64
 1   PerformanceRating         1470 non-null   int64
 2   EnvironmentSatisfaction   1470 non-null   int64
 3   JobInvolvement            1470 non-null   int64
 4   JobSatisfaction           1470 non-null   int64
 5   RelationshipSatisfaction  1470 non-null   int64
 6   WorkLifeBalance           1470 non-null   int64
dtypes: int64(7)
memory usage: 80.5 KB